.travis.yml, Command/ReindexCommand.php, Content/ArticleDataItem.php, Content/ArticleDataProvider.php, Content/ArticleResourceItem.php, Controller/ArticleController.php, Document/ArticleOngrDocument.php, Document/ExcerptOngrObject.php, Document/Index/ArticleIndexer.php, Document/MediaCollectionOngrObject.php, Document/SeoOngrObject.php, Document/Subscriber/ArticleSubscriber.php, Resources/config/services.xml, Tests/Functional/Content/ArticleDataProviderTest.php, Tests/Functional/Controller/ArticleControllerTest.php, Tests/app/config/config.yml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/2716
This PR add a smart-content data-provider.
=> Implemented data-provider for smart-content

Admin/ArticleJsConfig.php, Controller/TemplateController.php, Document/Index/ArticleIndexer.php, Document/Serializer/TypeSubscriber.php, Exception/RouteSchemaNotFoundException.php, Metadata/ArticleTypeTrait.php, Resources/config/services.xml, Routing/ArticleRouteGeneratorByTemplate.php, Routing/ArticleRouteGeneratorByType.php, Tests/Functional/Controller/ArticleControllerTest.php, Tests/Unit/Routing/ArticleRouteGeneratorByTemplateTest.php, Tests/Unit/Routing/ArticleRouteGeneratorByTypeTest.php, Tests/app/config/config.yml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/2820
This PR implements a by-type and by-template route-generator to individualize the generation of routes per-type or per-template.
~~~yml
sulu_route:
mappings:
Sulu\Bundle\ArticleBundle\Document\ArticleDocument:
generator: schema
options:
article: /article/{object.getTitle()}
lexicon: /lexicon/{object.getTitle()}
~~~
=> Implemented by-type and by-template route-generator

Controller/ArticleController.php, Document/ArticleOngrDocument.php, Document/Index/ArticleIndexer.php, Resources/public/dist/components/articles/edit/settings/form.html, Resources/public/js/components/articles/edit/settings/form.html, Teaser/ArticleTeaserProvider.php, Tests/Functional/Teaser/ArticleTeaserProviderTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/2846
This PR add the teaser attributes `structureType` and `type`.
=> Added teaser-attributes

Document/MediaCollectionOngrObject.php
| Q | A
| --- | ---
fixed error on first access because ids not contain the media ids.
=> Fix media ids in ongr media collection document

Controller/ArticleController.php
| Q | A
| --- | ---
Fixed order in list when column is camel case.
Order by column in camel case crashes the search in elastic search, because the names of the columns are normalized in elastic search.
=> [BUGFIX] Fixed sort order in elasstic serach with camelcase

composer.json
| Q | A
| --- | ---
| Fixed tickets | n/a
| Related issues/PRs | n/a
| Documentation PR | n/a
It allows to install the article bundle in a project with a stable Sulu, although there is no release of this bundle yet
Because now it is hard to start using the article bundle in a project. One has to provide version aliases.
=> Allow stable sulu (1.4)

.styleci.yml, Content/ArticleDataProvider.php
| Q | A
| --- | ---
We have introduced objects in search-index and in the smart-content data-provider it was missing.
=> Fixed smart-content query for categories and tags

Content/ArticleResourceItem.php
| Q | A
| --- | ---
This PR allows direct access to resource-item in smart-content resource-item.
It is faster to use the view object that loading the document. The view-document is already there and can be extended with things that will be loaded.
=> Added methods to article-resource-item

Content/ArticleDataProvider.php, Tests/Functional/Content/ArticleDataProviderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #61
This PR fixes the flag `hasNextPage` in `ArticleDataProvider`
=> Fixed has-next-page in article data-provider

README.md, Resources/doc/installation.md
| Q | A
| --- | ---
This PR moves the actual content to `Resources/doc/installation.md` and places general informations in the `README.md` file. This restructure allows us to extend the doc in the future without spaming in the `README.md`.
=> Moved installation notes to doc

Document/ArticleDocument.php, Document/Behavior/RoutableBehavior.php, Document/Subscriber/ArticleSubscriber.php, Document/Subscriber/RoutableSubscriber.php, Resources/config/services.xml, Tests/Functional/Controller/ArticleControllerTest.php, Tests/Unit/Document/Subscriber/ArticleSubscriberTest.php, Tests/Unit/Document/Subscriber/RoutableSubscriberTest.php
| Q | A
| --- | ---
This PR improves the separation of concerns by extracting the route-stuff from the article subscriber.
This part will be used also for the pages afterwards in the multi-page feature.
=> Extracted routable-behavior from article-subscriber

Controller/WebsiteArticleController.php, Resources/config/services.xml, Routing/ArticleRouteDefaultProvider.php, Tests/Unit/Routing/ArticleRouteDefaultProviderTest.php, UPGRADE.md
| Q | A
| --- | ---
Add caching and sulu twig parameters.
Articles are currently not cached.
_cacheLifetime will  return the seconds instead of whole cacheLifetime array.
=> Add caching headers and sulu twig parameters

Content/ArticleSelectionContentType.php, Controller/ArticlePageController.php, DependencyInjection/SuluArticleExtension.php, Document/ArticleDocument.php, Document/ArticlePageDocument.php, Document/ArticlePageViewObject.php, Document/ArticleViewDocument.php, Document/ArticleViewDocumentInterface.php, Document/Form/ArticleDocumentType.php, Document/Form/ArticlePageDocumentType.php, Document/Index/ArticleIndexer.php, Document/Initializer/ArticleInitializer.php, Document/Initializer/ArticlePageNodeType.php, Document/Serializer/ArticlePageSubscriber.php, Document/Structure/ArticlePageBridge.php, Document/Subscriber/ArticlePageSubscriber.php, Document/Subscriber/ArticleSubscriber.php, Exception/ParameterNotAllowedException.php, Resources/config/routing_api.xml, Resources/config/serializer/Document.ArticlePageDocument.xml, Resources/config/services.xml, Resources/doc/installation.md, Tests/Functional/Controller/ArticleControllerTest.php, Tests/Functional/Controller/ArticlePageControllerTest.php, Tests/Unit/Document/Subscriber/ArticlePageSubscriberTest.php, Tests/Unit/Document/Subscriber/ArticleSubscriberTest.php, Tests/app/Resources/articles/default_pages.xml, Tests/app/config/config.yml
| Q | A
| --- | ---
This PR introduces a `ArticlePageDocument`. This documents will be saved as childs of `ArticleDocuments`. 
This is the first part of the "Multi-Page" feature.
=> Implemented page document and API

Document/Index/ArticleIndexer.php
| Q | A
| --- | ---
| Fixed tickets | fixes #108 
This PR fixes the clear of article index. it will execute search until no document will be returned. This ensures that all documents will be removed before reindexing.
=> Fixed clear all article view documents

Content/ArticleDataProvider.php
| Q | A
| --- | ---
| Fixed tickets | fixes #115
This PR fixes the issue that in the backend only 10 elements will be displayed if no limit isset. This is the default of elasticsearch.
=> Added high limit if no limit isset

Document/Index/ArticleGhostIndexer.php, Document/Index/ArticleIndexer.php
| Q | A
| --- | ---
This PR moves the persist call after the index event to ensure persisting changes in the event.
Changes in the event were not persisted.
=> Fixed call persist after article-listener

DependencyInjection/SuluArticleExtension.php, Document/ArticlePageDocument.php, Document/Behavior/PageBehavior.php, Document/Subscriber/ArticlePageSubscriber.php, Document/Subscriber/PageSubscriber.php, Document/Subscriber/RoutableSubscriber.php, Resources/config/services.xml, Routing/ArticlePageRouteGenerator.php, Tests/Unit/Document/Subscriber/ArticlePageSubscriberTest.php, Tests/Unit/Document/Subscriber/PageSubscriberTest.php, Tests/Unit/Document/Subscriber/RoutableSubscriberTest.php, Tests/Unit/Routing/ArticlePageRouteGeneratorTest.php
| Q | A
| --- | ---
| Related issues/PRs | build ontop #122 
This PR adds the route to article-page.
=> Added route-behavior to article-page

Command/ReindexCommand.php
| Q | A
| --- | ---
This PR fixes the reindex command to only reindex published articles.
=> Fixed reindex only published article for live

.travis.yml, Controller/ArticlePageController.php, Document/ArticleDocument.php, Document/ArticlePageDocument.php, Document/Behavior/RoutableBehavior.php, Document/Behavior/RoutablePageBehavior.php, Document/Index/ArticleIndexer.php, Document/Subscriber/PageSubscriber.php, Document/Subscriber/RoutableSubscriber.php, Resources/config/serializer/Document.ArticleDocument.xml, Resources/config/serializer/Document.ArticlePageDocument.xml, Resources/config/services.xml, Tests/Functional/Controller/ArticlePageControllerTest.php, Tests/Unit/Document/Subscriber/PageSubscriberTest.php, Tests/Unit/Document/Subscriber/RoutableSubscriberTest.php, composer.json
| Q | A
| --- | ---
| Related issues/PRs | build ontop #122 https://github.com/sulu/sulu/pull/3299
This PR changes the time to generate the route to on-publish which allows us to detect deleted nodes and remove their routes.
=> Changed generating route only on publish

Document/Subscriber/ArticlePageSubscriber.php, Document/Subscriber/ArticleSubscriber.php, Document/Subscriber/RoutableSubscriber.php, Tests/Unit/Document/Subscriber/RoutableSubscriberTest.php
| Q | A
| --- | ---
This PR fixes the metadata of articles to sync remove live.
=> Fixed metadata for article to sync remove

Resources/config/serializer/Document.ArticleDocument.xml
| Q | A
| --- | ---
Set the article authored format to `Y-m-d`.
Else it dont work without the intl extension.
=> Fixed saving of articles without intl extension

Document/Subscriber/RoutableSubscriber.php
| Q | A
| --- | ---
Use correct locale when removing page child urls.
Currently the false locale is used when removing the child routes.
=> Fix remove of child route for page tree route

Document/Subscriber/RoutableSubscriber.php
| Q | A
| --- | ---
Use exist route object when document has one.
Avoid errors in imports when document is persisted multiple times.
=> Use exist route object for route generation

Document/Subscriber/PageTreeRouteSubscriber.php, Tests/app/Resources/articles/page_tree_route_second.xml
| Q | A
| --- | ---
Fixes the query to find articles when a page was published (or moved) when multiple templates uses the `page-tree-route` content-type.
=> Fixed find linked articles query when multiple templates exists

PageTree/PageTreeRouteUpdateHandler.php, composer.json
| Q | A
| --- | ---
| Related issues/PRs | requires https://github.com/php-task/TaskBundle/pull/39
This PR uses the locking component to avoid concurency.
=> Added LockingTaskHandlerInterface to update handler-class

Controller/WebsiteArticleController.php, composer.json
| Q | A
| --- | ---
Set maxAge and sharedMaxAge in the website article controller.
As it is require for the symfony cache to have a max and shared max age for caching.
=> Fix caching for website articles

DependencyInjection/SuluArticleExtension.php, Tests/Functional/Controller/ArticleControllerTest.php, Tests/app/AppKernel.php, composer.json
| Q | A
| --- | ---
| Fixed tickets | fixes --
Creates sulu document proxy directories if they don`t exists.
Not working with Sulu >= 1.6.*
=> Check if cache directories of sulu exist

Content/ArticleResourceItem.php
| Q | A
| --- | ---
| Fixed tickets | fixes --
ArticleResourceItem:
Corrected `getChanger` and `getCreator`.
Also added `getPublished`.
`getChanger` and `getCreator` were not working correctly.
=> ArticleResourceItem: Use correct properties of ArticleViewDocument

PageTree/PageTreeUpdater.php
| Q | A
| --- | ---
This PR fixes the `PageTreeUpdater` which throws an exception if no template uses this content-type.
=> Fixed page-tree-updater if no template uses the page-tree

Document/Subscriber/RoutableSubscriber.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/3411
Reset the target when not an history url.
Else it still have a target but is no history.
~~~php
$route->setHistory(false);
$route->setTarget(null);
~~~
=> Reset route target when no history url

DependencyInjection/SuluArticleExtension.php, Resources/doc/installation.md
| Q | A
| --- | ---
This PR enhances the configuration at installation time. It makes the config for article_page obsolete and prepended (or better appended) by the article-extension.
=> Append config for article-page in article-extension

.travis.yml, Content/PageTreeRouteContentType.php, Resources/config/services.xml, Tests/Functional/Content/PageTreeRouteContentTypeTest.php, Tests/Functional/Controller/ArticleControllerTest.php
| Q | A
| --- | ---
This PR saves the webspace on the article when saving the `PageTreeContentType`.
=> Added webspace to node when saving page-tree content-type

PageTree/PageTreeUpdater.php
| Q | A
| --- | ---
This PR fixes the page-tree-updater to set also to new document uuid.
=> Fixed page-tree-updater to also set the uuid of the new page

Command/MovePageTreeCommand.php, DependencyInjection/SuluArticleExtension.php, PageTree/PageTreeMoverInterface.php, PageTree/PageTreeRepository.php, Resources/config/page_tree_move.xml, Resources/config/page_tree_update.xml, Resources/doc/routing.md, Tests/Functional/PageTree/PageTreeRepositoryTest.php
| Q | A
| --- | ---
| Related issues/PRs | built ontop of https://github.com/sulu/SuluArticleBundle/pull/208
This PR adds a command to move articles from one parent-page to another one.
If you remove a page in the page tree. The articles will be detached from the page (URL stays the same) and you can choose a new page when you edit the Article. But if you want to do this for all the affected Articles there is no way to do it in a single step.
This PR adds the command and the functionality todo that. Later this functionality can be triggered by the content-manager from the UI (additional later PR when needed).
~~~bash
bin/console sulu:article:page-tree:move /page-1 /page-2 …
=> Implemented page-mover command

Builder/ArticleIndexBuilder.php, DependencyInjection/SuluArticleExtension.php, Resources/config/services.xml
| Q | A
| --- | ---
| Fixed tickets | fixes #198
This PR adds an `article_index` builder. create index on build time when `--destroy` flag isset a created index will also be dropped.
=> Added index-builder

Resources/translations/sulu/backend.de.xlf, Resources/translations/sulu/backend.en.xlf, Resources/translations/sulu/backend.fr.xlf, Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
This PR adds a missing translation key for category-selection overlay.
=> Added missing translation for category-selection

Document/Subscriber/RoutableSubscriber.php, Tests/Functional/Controller/ArticleControllerTest.php
| Q | A
| --- | ---
This PR fixes a problem when reordering pages of an article. The resulting URLs looks like `/test-article/page-2-1`
The conflicts were resolved when on reorder.
=> Fixed reorder route generation

DependencyInjection/SuluArticleExtension.php, Document/ArticlePageDocument.php, Resources/config/automation.xml, Resources/config/services.xml, Routing/ArticleRouteDefaultProvider.php
| Q | A
| --- | ---
Make it possible to override article and article page documents
Was currently not possible:
```xml
sulu_document_manager:
mapping:
article_page:
class: AppBundle\Document\ArticlePageDocument
phpcr_type: 'sulu:articlepage'
mapping: {  }
```
=> Make it possible to override article and article page documents

Document/Subscriber/ArticleSubscriber.php
| Q | A
| --- | ---
This PR removes live-indexing when article-page was removed.
This action creates a draft and the live-index will be updated on publishing. so this is not needed when deleting the page.
=> Fixed remove page and live-index

PageTree/PageTreeRouteUpdateHandler.php, Resources/config/automation.xml, Tests/Unit/PageTree/PageTreeRouteUpdateHandlerTest.php, composer.json
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/php-task/php-task/pull/39 https://github.com/php-task/TaskBundle/pull/41
This PR uses `RetryEcxeption` to restart the handler if an unexpected occurs
Long running processes seems to break of several reasons
=> Added transaction handling for route-update

Document/Index/ArticleIndexer.php, Document/Index/IndexerInterface.php, Document/Subscriber/ArticleSubscriber.php, Tests/Functional/Document/Index/ArticleIndexerTest.php
| Q | A
| --- | ---
This PR fixes the problem that the admin-index will not be updated when unpublishing articles. This will lead into a wrong state in the list.
=> Fixed unpublish article does not update admin-index

Command/ReindexCommand.php, Document/Index/ArticleIndexer.php, Document/Index/IndexerInterface.php, Resources/doc/README.md, Resources/doc/commands.md, UPGRADE.md
| Q | A
| --- | ---
| Fixed tickets | fixes #135
This PR refactored the reindex command to index all locales at once. Additionally, the option `drop` was introduced to drop and recreate the whole index.
This will increase the developer experience with reindexing the articles.
```bash
bin/adminconsole sulu:article:reindex --drop
bin/websiteconsole sulu:article:reindex --drop
```
Output:
```bash
$ bin/websiteconsole sulu:article:reindex --drop
Reindex articles for the `website` context
ATTENTION: This operation drops and recreates the whole index and deletes the complete data.
Are you sure you want to drop the index? y
Dropped and recreated index for the `website` context …
```
=> Refactored reindex command

Document/Serializer/ArticleWebsiteSubscriber.php, Tests/Unit/Document/Subscriber/ArticleWebsiteSubscriberTest.php
| Q | A
| --- | ---
This PR adds a check for `ArticlePageDocument`.
Unpublish pages creates error because of unknown document.
=> Added check for article-page-document

Markup/ArticleLinkProvider.php, Tests/Functional/Markup/ArticleLinkProviderTest.php
| Q | A
| --- | ---
This PR fixes the search-query size for article-links count more than 10 (auto size of 10 in elasticsearch)
=> Fixed article link provider for more than ten links

Document/Index/ArticleIndexer.php
| Q | A
| --- | ---
This PR adds a check foe existence of index (before dropping it) to avoid crash of reindex command.
=> Added check for existence when dropping the index

Builder/ArticleIndexBuilder.php, Document/Index/ArticleIndexer.php
| Q | A
| --- | ---
The cache clear need to be removed for 1.6.9
This was removed for symfony 3.4 in sulu/sulu.
=> Fix drop index on none exist and remove ArticleIndexBuilder dependency on cache builder

Resources/translations/sulu/backend.nl.xlf
The old translation wasn't correct in Dutch, it translated roughly as "Me article". This updates it to "My articles"
=> Improve "My articles" translations NL

Resources/doc/installation.md
| Q | A
| --- | ---
Add text that it need to be registered after the SuluDocumentManager Bundle
Error when registered before the SuluDocumentManager.
=> Update documentation where article bundle should be registered

Document/Structure/ArticleBridge.php, Document/Structure/ArticlePageBridge.php, Document/Structure/ContentProxyFactory.php, Resources/config/services.xml, Tests/Unit/Document/Subscriber/ArticleWebsiteSubscriberTest.php, composer.json
| Q | A
| --- | ---
| Fixed tickets | fixes #307 
This pull-request add the webspace-key to article-structure.
This is necessary because some content-types (snippet for example) uses it.
=> Added webspace-key to article- and article-page-bridge

DependencyInjection/SuluArticleExtension.php
| Q | A
| --- | ---
This PR adds a check for `SuluAutomationBundle` to enable task cascade.
=> Added check for automation-bundle before task is available

.circleci/config.yml, Controller/ArticlePageController.php, DependencyInjection/SuluArticleExtension.php, Document/ArticleDocument.php, Document/ArticlePageDocument.php, Document/Subscriber/ArticlePageSubscriber.php, Resources/doc/installation.md, Resources/doc/multi-page.md, Resources/doc/routing.md, Tests/Functional/Controller/ArticleControllerTest.php, Tests/Functional/PageTree/PageTreeRepositoryTest.php, Tests/TestExtendBundle/Document/ArticleDocument.php, Tests/TestExtendBundle/Document/ArticlePageDocument.php, Tests/TestExtendBundle/TestExtendBundle.php, Tests/app/AppKernel.php, Tests/app/config/config.yml, Tests/app/config/config_default.yml, Tests/app/config/config_extend.yml, UPGRADE.md
| Q | A
| --- | ---
Use correct class for generating routes.
Currently there is a mix between classes when you extend the ArticleDocument and ArticlePageDocument.
=> Fix route generation in correct class

Content/ArticleSelectionContentType.php, Tests/Unit/Content/ArticleSelectionContentTypeTest.php
| Q | A
| --- | ---
Fixes the limit of the article selection content type as the default value was 10.
=> Fixed limit for article selection content type

Controller/ArticleController.php
| Q | A
| --- | ---
Change the `getFieldDescriptors` method in the ArticleController Class from private to protected
If you want to build your own article overview list.
Overwrite the ArticleController in the routing and set own fields in `getFieldDescriptors`
=> Changed getFieldDescriptors from private to protected

.circleci/config.yml, ListBuilder/ElasticSearchFieldDescriptor.php, ListBuilder/ElasticSearchFieldDescriptorBuilder.php, Resources/config/services.xml, UPGRADE.md
| Q | A
| --- | ---
Fix contact repository deprecations.
sulu_contact.contact_repository was removed and the fielddescriptor constructor changed.
=> Fix contact repository deprecations and fielddescriptor searchability

Document/Subscriber/ArticlePageSubscriber.php, Tests/Functional/Controller/ArticlePageControllerTest.php
| Q | A
| --- | ---
ArticlePages cannot be published because ArticleDocument (parent of article-page) is a proxy and therfor the route cannot be found.
=> Fixed article page publish by hydrating parent-document

.travis.yml, composer.json
| Q | A
| --- | ---
| Related PRs | ~https://github.com/sulu/SuluAutomationBundle/pull/19~
Set correct symfony requirements and branch alias for 2.0.
Allow to install article bundle as ^2.0@dev
=> Set branch alias for 2.0 require correct sulu version and specific symfony packages

Document/ArticleViewDocument.php, Document/ArticleViewDocumentInterface.php, Tests/Functional/Controller/ArticleControllerTest.php, Tests/Functional/Controller/ArticlePageControllerTest.php, Tests/Functional/PageTree/PageTreeRepositoryTest.php, composer.json
| Q | A
| --- | ---
Added support ongr newest version after a bc break in ongr ( https://github.com/ongr-io/ElasticsearchBundle/pull/777 )
To support needed fixes of 5.0.6.
=> Fixed incompatibility with ongr/elasticsearch 5.0.6

Resources/translations/sulu/backend.de.xlf, Resources/translations/sulu/backend.en.xlf, Resources/translations/sulu/backend.fr.xlf, Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
This PR pluralize the menu entry for the articles, by replacing "Article" with "Articles".
Most entries are already pluralized: "Snippets", "Users", ... the goal of this PR is to use the same convention on this entry.
By the way I don't speak german or dutch, so I'm not 100% sure of the pluralization here.
=> Pluralize menu entry

Resources/doc/article-types.md
| Q | A
| --- | ---
| Fixed tickets | fixes #334 
A simple documentation typo fix
=> Fix Smart-Content syntax in documentation example

.travis.yml, DependencyInjection/Configuration.php
| Q | A
| --- | ---
Added debug output for composer install for php 5.5.
Fix incompatibility to symfony < 3.3 with arrayPrototype.
To avoid stalled build on travis and fix compatibility to symfony <3.3.
=> Fix travis for php 5.5 and symfony < 3.3 compatibility

.circleci/config.yml, .travis.yml, Document/Form/ArticleDocumentType.php, Document/Form/UnstructuredType.php, composer.json
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/4349
Use unstructured form type for extensions to avoid an error which happens with only scalar values mapping for TextType. And test article bundle as on php 7.3 as now elasticsearch client supports.
Fix compatibility to symfony 3.4.21
=> Fix compatibility to symfony 3.4.21

.travis.yml, Sitemap/ArticleSitemapProvider.php
| Q | A
| --- | ---
This PR enhances the possibility to overwrite the sitemap provider.
When using an own sitemap-template its neccessary to add attributes to a single `SitemapUrl`.
=> Add protected function to allow overwrite the sitemap-url creation

README.md
| Q | A
| --- | ---
| Related issues/PRs | #378
Remove conflict with elasticsearch 6.
There is not longer a conflict with es6.
=> Remove conflict with elasticsearch 6

Admin/ArticleAdmin.php, Controller/ArticleController.php
| Q | A
| --- | ---
Disabled the preview for articles in the Sulu admin.
The preview is not implemented at the moment and therefore an error (dev environment) or an empty preview (prod environment) is shown which is confusing for the user.
=> Removed preview

Admin/ArticleAdmin.php, Controller/WebsiteArticleController.php
| Q | A
| --- | ---
| Fixed tickets | ---
| Related issues/PRs | ---
Previously the Preview in the ArticleBundle always rendered the complete site. This PR will change that, so that appending the `preview` and `partial` flags will have the same effects as in the Controller for pages.
Because the new Preview requires this functionality.
=> Add preview mode to WebsiteArticleController

DependencyInjection/SuluArticleExtension.php, Resources/doc/installation.md, Tests/Application/config/config.yml
| Q | A
| --- | ---
Removed analysis from ONGR ElasticSearch config.
To fix configuration issues.
=> Avoid prepend of ongr analyzers

Document/Index/ArticleGhostIndexer.php
| Q | A
| --- | ---
Dispatches the index event for ghost articles.
To allow programmers to edit or add fields before indexing them.
=> Dispatch index event for ghost articles

Content/ArticleDataProvider.php, Content/PageTreeArticleDataProvider.php, Tests/Functional/Content/PageTreeArticleDataProviderTest.php
| Q | A
| --- | ---
Changes the `PageTreeArticleDataProvider` datasource from `articles` to `pages`.
Adjusts the sulu-translations to existing ones.
Adds a test for sorting the smart-content for title.
Because the datasource for the `PageTreeArticleDataProvider` should be a page and not articles.
=> Update PageTreeArticleDataProvider datasource and translation keys

Admin/ArticleAdmin.php
| Q | A
| --- | ---
This PR add the edit button to the article form and set the disables/visible conditions to the other buttons.
This is a missing feature in 2.0
=> Add edit dropdown button with remove draft and publish to toolbar

Resources/config/services.xml
| Q | A
| --- | ---
Adds the missing StructureManager to ArticleAdmin in the service configuration.
=> Add StructureManager to admin service configuration

Document/Subscriber/ArticleSubscriber.php
| Q | A
| --- | ---
Fix locale specific indexing of articles.
If you create in the same request or command an article in different languages the other language will accidently overwrite the first language and at the end the index result will not contain any urls strangely.
=> Fix locale specific indexing of articles

EventListener/ContentProxyListener.php
| Q | A
| --- | ---
Better error message when structure not longer exist.
When the Structure not longer exist the ContentProxyListener does currently throw a strange call `setUuid` on null error message.
=> Better error message when structure not longer exist

Command/ReindexCommand.php
| Q | A
| --- | ---
| Fixed tickets | fixes #352
This PR fixes the spelling of a variable.
| Step | Variable name
| --- | ---
| Before | $progessBar
| After | $prog**r**essBar
There is a typo in the variable name.
=> Fix typo in the variable name

composer.json
… work without the extension
| Q | A
| --- | ---
| Fixed tickets | -
Add the JSON extension of PHP to the composer.json file.
Please note the order of other entries change, too because the composer option "sort-packages" was ignored before. That'll likely happen when someone manually edits the file.
Although PHP ships with the JSON extension by default this may not be always the case.
https://www.php.net/manual/en/json.installation.php
It is better to check if the system fulfills the dependencies _before_ installing.
~~~bash
php -d memory_limit=1G composer.phar install
~~~
=> Add the JSON extension to composer.json

Command/ReindexCommand.php
| Q | A
| --- | ---
| Fixed tickets | fixes #464
Changes the return type of the `getDocuments` function because the current return type is wrong. See #464 for more information.
=> Fix return type in ReindexCommand

Controller/ArticleController.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/SuluArticleBundle/issues/462
Adds the ghostLocale attribute for articles, so that the frontend is able to show the ghost indicator
=> Add ghost indicator for articles

Controller/WebsiteArticleController.php
| Q | A
| --- | ---
| Fixed tickets | -
Method loadTemplate was deprecated in Twig 1.28 only for internal use, see this
https://twig.symfony.com/doc/1.x/api.html#rendering-templates and https://twig.symfony.com/doc/1.x/tags/include.html 
With Twig 3.0 this method fail:
```
Too few arguments to function Twig\Environment::loadTemplate(), 1 passed in /var/www/html/vendor/sulu/article-bundle/Controller/WebsiteArticleController.php on line 162 and at least 2 expected
```
No BC Breaks. This bundle requires ^1.41
=> Use load instead LoadTemplate for compatibility with Twig 3

Document/Index/Factory/ExcerptFactory.php
| Q | A
| --- | ---
The images/icons of the excerpt can be empty by the database.
The MediaCollectionFactory requires the array type for the data parameter.
=> Fix nullable excerpt images

Document/MediaViewObject.php, UPGRADE.md
| Q | A
| --- | ---
The index data of the formats field can be to long for the default configuraiton of version 6.8.
=> Fix mapping of article-media object

Search/ArticleSearchSubscriber.php
| Q | A
| --- | ---
| Related issues/PRs | #486
Set article routePath as url in the ArticleSearchSubscriber.
To get the correct article url for the search.
=> Set routePath as URL for the search

Resources/doc/default.html.twig, Resources/doc/installation.md
| Q | A
| --- | ---
| Fixed tickets | ---
| Related issues/PRs | ---
This PR adjusts the installation instructions that are not true anymore.
Because otherwise people receive an error while running them, which might confuse them.
=> Remove installation instructions that are not necessary anymore

.circleci/config.yml, .travis.yml, README.md, Resources/doc/installation.md, composer.json
| Q | A
| --- | ---
| Fixed tickets | fixes #431, fixes #485 
| Related issues/PRs | https://github.com/ongr-io/ElasticsearchBundle/pull/909,  <br/> https://github.com/ongr-io/ElasticsearchDSL/pull/324, <br/> https://github.com/ongr-io/ElasticsearchBundle/pull/946
Test Travis with ES7.
Add support for elasticsearch 7.
Use ES7 and run tests.
=> Add support for elasticsearch 7

Content/PageTreeArticleDataProvider.php, Tests/Functional/Content/PageTreeArticleDataProviderTest.php
…ntent
| Q | A
| --- | ---
Fix elasticsearch error for no resource segment in page tree smart co….
You get a strange elasticsearch error if you `PrefixQuery` is used with a `null` value.
=> Fix elasticsearch error for no resource segment in page tree smart content

Content/ArticleDataProvider.php, Tests/Functional/Content/ArticleDataProviderTest.php
| Q | A
| --- | ---
The defaultLimit should not have any effect on paginated smart content it should just limit the pageSize not the whole totals.
Currently pagination over the default limit doesn't work and will not return all articles. So for example a smart content with `12` per page and 118 articles will just return the first 100 articles, show hasNextPage as true but will fail with OutofBoundException on Page 10.
=> Fix pagination default limit for smart content

.travis.yml, DependencyInjection/StructureValidatorCompilerPass.php, DependencyInjection/SuluArticleExtension.php, Resources/doc/installation.md, Tests/Application/config/templates/articles/default_pages.xml
| Q | A
| --- | ---
| Related issues/PRs | #473 
Remove template default type definition.
> Attention this is currently just a workaround for multiple type issue!!!
The hack should be removed when https://github.com/sulu/sulu/pull/5381 is merged.
The default type definition does not work with multiple article types.
=> Remove template default type definition

Controller/ArticleController.php, Tests/Functional/Controller/ArticleControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #474
Fix filter by multiple types.
Currently the types filter has no effect when give more than one.
=> Fix filter by multiple types

Resources/doc/default.xml, Tests/Application/config/templates/articles/default_pages.xml, Tests/Application/config/templates/articles/default_with_route.xml
It looks like the `sulu_article.article_title` is not used in the codebase of the bundle. Therefore, I dont think we should include it in our templates.
=> Remove unused sulu_article.article_title from article templates

Document/Index/ArticleIndexer.php
| Q | A
| --- | ---
| Fixed tickets | fixes #492
| Related issues/PRs | #492
Changed the translation domain from 'backend' tot 'admin'
=> Changed translation domain from backend to admin

Command/ArticleExportCommand.php, Export/ArticleExport.php, Export/ArticleExportInterface.php, Export/ExportFormatNotFoundException.php, Resources/config/services.xml, Resources/doc/README.md, Resources/doc/xliff.md, Resources/views/Export/Article/1.2.xliff.twig, Resources/views/Export/Article/base.export.twig, Tests/Functional/Controller/ArticleControllerTest.php, Tests/Functional/Export/ArticleExportTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/5494
This PR add a command to export the articles as xliff export. In a following PR it will be possible to import the translated file again.
It should be possible to use the exported file to translate the articles with a tool or a translation agency.
~~~bash
$ bin/adminconsole sulu:article:export export.xliff en
Article Language Export
=======================
Options
Target: export.xliff
Locale: en
Format: 1.2.xliff
---------------
Continue with this options?(y/n) y
Continue!
Loading Data…
30/30 [============================] 100%
Render Xliff…
~~~
=> Add xliff export for articles

Document/ArticleViewDocument.php, Elasticsearch/AnnotationReader.php, Resources/config/services.xml, Resources/doc/article-view-document.md, Tests/Functional/Controller/ArticleControllerTest.php, Tests/Functional/Controller/ArticlePageControllerTest.php, Tests/Functional/Document/Index/ArticleIndexerTest.php, Tests/TestExtendBundle/Document/ArticleViewDocument.php, Tests/app/config/config_extend.yml, composer.json
| Q | A
| --- | ---
| Related issues/PRs | requires https://github.com/handcraftedinthealps/ElasticsearchBundle/pull/12
Add flag to enable/disable mapping prepend of the ongr bundle config.
When you add your own ViewDocument both "types" will be mapped and that ends up in an exception from elasticsearch.
=> Add annotation reader to dynamically add the document annotation

Content/ArticleDataProvider.php, Controller/WebsiteArticleController.php, Document/ExcerptViewObject.php, Document/Index/Factory/ExcerptFactory.php, Document/Index/Factory/SegmentCollectionFactory.php, Document/SegmentViewObject.php, Resources/config/services.xml, Tests/Functional/Content/ArticleDataProviderTest.php, Tests/Functional/Controller/ArticleControllerTest.php, UPGRADE.md
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/5425
This PR adjusts the `ArticleDataProvider` of the bundle to respect the current segment when filtering articles. With this PR, the `ArticleDataProvider` will return an article only if it is not assigned to a segment for the current webspace or if it is assigned to the current segment for the current webspace.
Because the `ArticleDataProvider` should behave similar to the `PageDataProvider`.
=> Filter articles based on current segment in ArticleDataProvider

Controller/ArticleController.php, Tests/Functional/Controller/ArticleControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/5573
This PR adjusts the `ArticleController` to use the given `src` locale when invoking the `copy-locale` action. Sulu added a `src` locale in https://github.com/sulu/sulu/pull/5573
=> Adjust copy-locale action of ArticleController to use given source-locale

Controller/WebsiteArticleController.php, Document/Serializer/WebsiteArticleUrlsSubscriber.php, Resources/config/services.xml, Tests/Unit/Document/Serializer/WebsiteArticleUrlsSubscriberTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #525
The following change overwrites the `urls` that are set by the `WebsiteArticleUrlsSubscriber`:
https://github.com/sulu/SuluArticleBundle/pull/511/files#diff-db580230ef3c42850622b9d5b0a46103221a92c430883ee4e19427d4e2632c8eR67-R72
Because of this, the rendering of alternate links does not work at the moment. See #525.
Additionally, Sulu now uses a `localizations` array instead of the `urls` per default. Therefore we need to add the `localizations` to the serialization too.
=> Pass urls and localizations array to twig template

README.md, Resources/doc/installation.md
When using `^7.9`, composer will install `7.10` when executing `composer update`
=> Adjust elasticsearch/elasticsearch version constraint in docs
