- .travis.yml
- Controller/ArticleController.php
- Document/ArticleOngrDocument.php
- Document/Index/ArticleIndexer.php
- Document/MediaCollectionOngrObject.php
- EventListener/ArticleOngrDocumentSerializeSubscriber.php
- Resources/config/services.xml
- Resources/translations/sulu/backend.de.xlf
- Resources/translations/sulu/backend.en.xlf
- Resources/translations/sulu/backend.fr.xlf
- Teaser/ArticleTeaserProvider.php
- Tests/Functional/Teaser/ArticleTeaserProviderTest.php
- Tests/app/Resources/articles/default_fallback.xml
- Tests/travis.php.ini
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/2715
This PR introduces a teaser-provider.
> Added teaser-provider

- Controller/ArticleController.php
- Document/ArticleOngrDocument.php
- Document/ExcerptOngrObject.php
- Document/SeoOngrObject.php
| Q | A
| --- | ---
| Fixed tickets | nonoe
This extends the mapping with `not_analyzed` raw fields
> Updated mapping for elastic index

- Document/ExcerptOngrObject.php
- Document/Index/ArticleIndexer.php
- Document/MediaCollectionOngrObject.php
- Document/MediaOngrObject.php
- Resources/config/services.xml
- Tests/Functional/Controller/ArticleControllerTest.php
| Q | A
| --- | ---
Add medias with title, url and thumbnails to index
So it need only to load the media when a article is changed.
> Add medias with title, url and thumbnails to index

- Resources/config/serializer/Document.ArticleViewDocument.xml
| Q | A
| --- | ---
This PR introduces the exclusion-policy to fix slow performance in lists.
> Changed exclusion-policy to all

- Document/CategoryViewObject.php
- Document/ExcerptViewObject.php
- Document/Index/ArticleIndexer.php
- Document/Index/Factory/CategoryCollectionFactory.php
- Document/Index/Factory/ExcerptFactory.php
- Document/Index/Factory/MediaCollectionFactory.php
- Document/Index/Factory/MediaFactory.php
- Document/Index/Factory/SeoFactory.php
- Document/Index/Factory/TagCollectionFactory.php
- Document/TagViewObject.php
- Resources/config/serializer/Document.ArticleDocument.xml
- Resources/config/services.xml
| Q | A
| --- | ---
Index Excerpt categories with keywords and tags.
Refactoring the ArticleIndexer.
Because its awesome.
> Extension index factory and artice indexer clean up

- Controller/ArticleController.php
- Tests/Functional/Controller/ArticleControllerTest.php
| Q | A
| --- | ---
Fix problem when search with uppercase values.
> Fix search when unter uppercase values

- Document/Index/ArticleIndexer.php
| Q | A
| --- | ---
This PR fixes the clear function to not drop the index
> Removed drop index on clear

- Resources/config/services.xml
| Q | A
| --- | ---
Fixes the proxy cache dir.
> Fixed proxy-cache-dir

- Document/Index/Factory/SeoFactory.php
- Document/SeoViewObject.php
- Resources/config/services.xml
- Sitemap/ArticleSitemapProvider.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/2916
This PR introduces a sitemap-provider for articles
> Added sitemap provider

- README.md
| Q | A
| --- | ---
| Fixed tickets | -
| Documentation PR | -
Explain the contents of the PR.
This PR updates the README.md to the latest configuration format.
> updated readme to latest configuration format

- Admin/ArticleContentNavigationProvider.php
- Controller/WebsiteArticleController.php
- README.md
- Resources/config/services.xml
- Resources/doc/article_default.html.twig
- Resources/doc/article_default.xml
| Q | A
| --- | ---
Added default WebsiteArticleController.
Better README for configuring bundle.
Added examples for structure and template.
> Added WebsiteArticleController; Modified documentation; Added example files

- Sitemap/ArticleSitemapProvider.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/2962
Fixes constructor to fit changes in linked sulu-PR.
> Fixed constructor of sitemap-class

- Document/ArticleViewDocument.php
| Q | A
| --- | ---
Added keyword analyzer for type.
> Updated ongr meta-data

- Controller/ArticleController.php
| Q | A
| --- | ---
This PR fixes the search in the article-list where the search does not return any result because the field metadata as excpected. Additionally the used query in this PR improve the result by including the full record.
> Fixed list search by adding query-string-query

- Controller/ArticleController.php
| Q | A
| --- | ---
The introduced QuerySearchQuery (https://github.com/sulu/SuluArticleBundle/pull/37) is to in-explicite for searching i a list. I have detected that the original was not that wrong as i thought there was a missing boolean-query.
> Reintroduced wildcard-query to make search more explicite in article-api

- DependencyInjection/SuluArticleExtension.php
- Document/Structure/ArticleBridge.php
| Q | A
| --- | ---
Add custom structure bridge for article to get view from structure.
> Add custom structure bridge for articles

- DependencyInjection/SuluArticleExtension.php
- Resources/config/automation.xml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/3037
This PR activates the automation feature for articles.
> Added automation tab to article

- Controller/ArticleController.php
| Q | A
| --- | ---
Implemented security context.
> Implemented security context

- Document/Form/ArticleDocumentType.php
- Tests/travis.php.ini
- composer.json
| Q | A
| --- | ---
This PR allows extra fields in the api.
> Added options to allow extra fields

- .scrutinizer.yml
- .styleci.yml
- .travis.yml
- README.md
- composer.json
| Q | A
| --- | ---
This PR prepares files for 0.2.0 release.
> Prepared files for release 0.2.0

- Controller/ArticleController.php
| Q | A
| --- | ---
| Fixed tickets | fixes #87 
| Documentation PR | --
Fixed translation for author in list.
> Fixed translation for author in list

- .travis.yml
- README.md
- composer.json
| Q | A
| --- | ---
| Fixed tickets | fixes --
| Related issues/PRs |--
| Documentation PR | --
Changed dependency to Sulu 1.5 and also travis tests should run in 1.5 and dev-develop
> Dependency change Sulu

- .travis.yml
- composer.json
| Q | A
| --- | ---
| Fixed tickets | fixes #80 
This PR improves test-setup for travis.
Currently this cannot work until sulu has released `1.5.1`
> Improved testsetup

- Document/Index/ArticleIndexer.php
| Q | A
| --- | ---
This PR improves the indexer by using find.
> Find user with find function of repository

- Controller/ArticleController.php
- Controller/ArticlePageController.php
- Controller/VersionController.php
- DependencyInjection/SuluArticleExtension.php
- Exception/ArticlePageNotFoundException.php
- Resources/config/serializer/Document.ArticleDocument.xml
- Resources/config/serializer/Document.ArticlePageDocument.xml
- Tests/Functional/Controller/ArticlePageControllerTest.php
| Q | A
| --- | ---
| Related issues/PRs | build ontop #114
This improves the serialization contexts of article and article-page.
> Improved serialization context of article and article-page

- Document/Structure/ArticleBridge.php
- Resources/config/services.xml
- Routing/ArticleRouteDefaultProvider.php
- Tests/Unit/Routing/ArticleRouteDefaultProviderTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #110
This PR will enable SuluCollector to collect information about articles.
> Fixed sulu-profiler to display informations about article

- Document/ArticlePageViewObject.php
- Document/Behavior/RoutableBehavior.php
- Document/Index/ArticleIndexer.php
- Document/Subscriber/PageSubscriber.php
- Document/Subscriber/RoutableSubscriber.php
- Resources/config/serializer/Document.ArticlePageDocument.xml
- Resources/config/services.xml
- Tests/Functional/Controller/ArticleControllerTest.php
- Tests/Functional/Controller/ArticlePageControllerTest.php
- Tests/Unit/Document/Subscriber/PageSubscriberTest.php
- Tests/Unit/Document/Subscriber/RoutableSubscriberTest.php
| Q | A
| --- | ---
This PR fixes the priorities to generate correct routes with pagenumber.
> Fixed priorities of subscriber

- Document/Index/ArticleGhostIndexer.php
- Document/Index/ArticleIndexer.php
- composer.json
| Q | A
| --- | ---
| Fixed tickets | --
| Documentation PR | --
Fixed bug when removing an article and it still exists.
> Fixed bug when removing an article and it still exists

- .travis.yml
- Controller/ArticlePageController.php
- Document/ArticlePageDocument.php
- Document/Index/ArticleIndexer.php
- Document/Subscriber/ArticlePageSubscriber.php
- Resources/config/services.xml
- Tests/Unit/Document/Subscriber/ArticlePageSubscriberTest.php
- composer.json
| Q | A
| --- | ---
| Related issues/PRs | build ontop #122 requires https://github.com/sulu/sulu-document-manager/pull/110 and https://github.com/sulu/sulu/pull/3306
This PR fixes the property title (which should contain the article-title) and add a new property page-title.
> Fixed title property (article-title) and add page title property

- Controller/WebsiteArticleController.php
- Document/ArticleDocument.php
- Document/ArticleInterface.php
- Document/Serializer/ArticleSubscriber.php
- Document/Serializer/ArticleWebsiteSubscriber.php
- Document/Subscriber/ArticlePageSubscriber.php
- Document/Subscriber/ArticleSubscriber.php
- Document/Subscriber/PageSubscriber.php
- Resources/config/serializer/Document.ArticleDocument.xml
- Resources/config/serializer/Document.ArticlePageDocument.xml
- Resources/config/services.xml
- Resources/doc/article_default.html.twig
- Resources/doc/article_default.xml
- Routing/ArticleRouteDefaultProvider.php
- Tests/Unit/Document/Subscriber/ArticleSubscriberTest.php
- Tests/Unit/Document/Subscriber/PageSubscriberTest.php
- Tests/Unit/Routing/ArticleRouteDefaultProviderTest.php
| Q | A
| --- | ---
| Related issues/PRs | build ontop #122
This PR populates the article-page to the website.
> Added page-number argument to website-article-controller

- Controller/WebsiteArticleController.php
- Document/Serializer/ArticleWebsiteSubscriber.php
- Preview/ArticleObjectProvider.php
- Resources/config/serializer/Document.ArticleDocument.xml
- Tests/Unit/Preview/ArticleObjectProviderTest.php
| Q | A
| --- | ---
| Related issues/PRs | built on top #122
This PR fixes the preview for article-pages.
> Fixed preview-serialization of article pages

- Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
| Fixed tickets | fixes #127
Added the dutch language
> Added dutch language

- DependencyInjection/Configuration.php
- Document/Index/ArticleIndexer.php
| Q | A
| --- | ---
This PR adds a configuration value for `ArticlePageViewDocument`.
> Added configuration for article-page object

- Controller/WebsiteArticleController.php
| Q | A
| --- | ---
Extract some methods in the `WebsiteController` to reuse them independently.
> Extracted methods to allow easier normalization and serialization of article

- Teaser/ArticleTeaserProvider.php
| Q | A
| --- | ---
This PR simplifies the inheritance and extension of attributes for article-teaser.
> Refactored article teaser-provider to simplify the inheritance

- Content/ArticleDataItem.php
- Content/ArticleDataProvider.php
- Content/PageTreeArticleDataProvider.php
- DependencyInjection/Configuration.php
- DependencyInjection/SuluArticleExtension.php
- Resources/config/services.xml
- Resources/doc/README.md
- Resources/doc/content-types.md
- Tests/Functional/Content/PageTreeArticleDataProviderTest.php
- composer.json
| Q | A
| --- | ---
This PR introduces a data-provider which uses the page route (selected in the admin) to filter the articles.
> Added page-route-data-provider

- Resources/config/services.xml
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/3369
This PR uses the newly introduced global proxy-manager config.
> Reuse proxy-manager configuration from sulu

- Resources/translations/sulu/backend.nl.xlf
| Q | A
| --- | ---
Some Dutch translations
They where not available in Dutch yet
> Provide additional Dutch translations

- Document/Serializer/WebsiteArticleUrlsSubscriber.php
- Resources/config/services.xml
- Tests/Unit/Document/Serializer/WebsiteArticleUrlsSubscriberTest.php
| Q | A
| --- | ---
This PR adds the URLs parameter to serialization to avoid Sulu from generating this via the router.
> Added urls parameter to serialization

- Command/ReindexCommand.php
- Document/ArticleViewDocument.php
- Document/ArticleViewDocumentInterface.php
- Document/Index/ArticleIndexer.php
- Tests/Functional/Document/Index/ArticleIndexerTest.php
- UPGRADE.md
| Q | A
| --- | ---
This PR add the parent-page to index.
> Added parent page to index

- Resources/doc/installation.md
| Q | A
| --- | ---
| Fixed tickets | n/a
| Related issues/PRs | https://github.com/sulu/SuluArticleBundle/issues/201
A fix for a typo in the example 'Configure the routing'.
n/a
> Fix typo in installation instructions

- Resources/translations/sulu/backend.fr.xlf
| Q | A
| --- | ---
| Related issues/PRs | fixes #127 
This PR adds and fixes translations based on @rflorent
> Added french translations

- Content/PageTreeRouteContentType.php
| Q | A
| --- | ---
This PR fixes the content-route-type with null UUID.
> Fixed content-route-type to save with null uuid

- .travis.yml
- composer.json
| Q | A
| --- | ---
This PR prepares the composer.json file to for 0.6.0 release.
> Updated sulu dependency in composer.json

- Resources/doc/installation.md
- Resources/doc/installation_es2.md
| Q | A
| --- | ---
This PR fixes the documentation to use this bundle with es2.
> Fixed composer require for es2

- Document/Subscriber/RoutableSubscriber.php
- PageTree/PageTreeRepository.php
- Tests/Functional/PageTree/PageTreeRepositoryTest.php
| Q | A
| --- | ---
This PR fixes a problem of the article-pages when moving to another page.
> Fixed move page-tree for article-pages

- Document/Serializer/ArticleWebsiteSubscriber.php
- Resources/config/services.xml
| Q | A
| --- | ---
This PR adds the resolve of extension data on serialize time.
> resolved extension data on serialize

- Preview/ArticleObjectProvider.php
- Tests/Unit/Preview/ArticleObjectProviderTest.php
| Q | A
| --- | ---
The parent of pages in the preview is null.
> Fixed serialization of article-page for preview

- Markup/ArticleLinkProvider.php
- Resources/config/services.xml
- Tests/Functional/Markup/ArticleLinkProviderTest.php
| Q | A
| --- | ---
This PR fixes a problem with `ArticleLinkProvider` where all articles will be marked as invalid.
The way of finding articles for links was wrong.
> Fixed article-link provider for published

- Controller/ArticleController.php
- FieldDescriptor/ESFieldDescriptor.php
- ListBuilder/ElasticSearchFieldDescriptor.php
- Tests/Functional/Controller/ArticleControllerTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes #244 
Implemented ESFieldDescriptor to add the possibility to configure the sort field.
> Fixed not working sorting with ES >= 5.0

- Document/Subscriber/PageTreeRouteSubscriber.php
- PageTree/AutomationPageTreeUpdater.php
- Resources/config/automation.xml
- Tests/Unit/PageTree/AutomationPageTreeUpdaterTest.php
- composer.json
| Q | A
| --- | ---
This PR fixes a problem when saving a page. The scheme and the host cannot be null for tasks.
> Fixed page-tree-updater

- DependencyInjection/SuluArticleExtension.php
- composer.json
| Q | A
| --- | ---
| Fixed tickets | fixes #226 
| Related issues/PRs | requires sulu/sulu#3557
See main PR https://github.com/sulu/sulu/pull/3557
> Added config value to decorate index name

- Resources/doc/README.md
- Resources/doc/article-types.md
- Resources/doc/routing.md
| Q | A
| --- | ---
| Fixed tickets | fixes #223 , fixes #218 
This PR introduces documentation for article-types.
> Added article-types documentation

- Resources/doc/article-view-document.md
| Q | A
| --- | ---
This PR introduces documentation (and example) for: How to extend ArticleViewDocument?
> Added how to extend article-view document for documentation

- Controller/ArticleController.php
| Q | A
| --- | ---
| Fixed tickets | fixes #269 
This PR tries to improve searchability for title in the admin-list
Parts of words would not be found.
> Improved search query for articles

- Resources/doc/README.md
- Resources/doc/overview-page.md
| Q | A
| --- | ---
This PR introduces documentation for overview-pages.
> Added documentation for article-overview

- Resources/doc/overview-page.md
| Q | A
| --- | ---
This PR fixes the wording of the overview page doc.
> Fixed wording of overview page doc

- Admin/ArticleContentNavigationProvider.php
- Command/ReindexCommand.php
- Content/ArticleDataProvider.php
- Content/ArticleSelectionContentType.php
- Controller/ArticleController.php
- Controller/VersionController.php
- DependencyInjection/PageTreeCompilerPass.php
- DependencyInjection/SuluArticleExtension.php
- Document/Index/ArticleIndexer.php
- Document/Serializer/ArticleWebsiteSubscriber.php
- Document/Subscriber/ArticlePageSubscriber.php
- Document/Subscriber/ArticleSubscriber.php
- Preview/ArticleObjectProvider.php
- Resources/config/services.xml
- Routing/ArticleRouteDefaultProvider.php
- Tests/Unit/PageTree/AutomationPageTreeUpdaterTest.php
- Tests/app/AppKernel.php
- composer.json
| Q | A
| --- | ---
Run tests on symfony 3.
To test symfony 3 compatibility.
> Run tests with symfony 3

- Document/Serializer/ArticleWebsiteSubscriber.php
- Tests/Unit/Document/Subscriber/ArticleWebsiteSubscriberTest.php
| Q | A
| --- | ---
Resolve the merge conflict in the article website subscriber.
It crash the website subscriber.
> Resolve merge conflict in article website subscriber

- .travis.yml
- Content/ArticleDataProvider.php
- Document/MediaViewObject.php
- composer.json
- phpstan.neon
| Q | A
| --- | ---
Add phpstan analyzer to travis
Find common issues.
> Add phpstan for static code analysis to travis

- Controller/WebsiteArticleController.php
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/3652
This PR catches the exception when no template was found for request format.
> Added not-accepted response for not found request format templates

- DependencyInjection/SuluArticleExtension.php
- Resources/config/services.xml
- composer.json
| Q | A
| --- | ---
This PR allows also 2.0 of jms/serializer-bundle.
> Updated jms-bundle

- Document/ArticleDocument.php
- Resources/phpcr-migrations/Version201712041018.php
- UPGRADE.md
| Q | A
| --- | ---
| BC breaks? | yes
This PR add the locale to author/authored field. This is a BC break but an UPGRADE script will be provided.
Currently the authored cannot be different in the other locales.
The authored dates have to be copied to all published locales.
> Added localized author behavior

- Builder/ArticleIndexBuilder.php
| Q | A
| --- | ---
This PR removes the dependency to cache builder (removed in sulu).
> Removed dependency to cache-builder

- Admin/ArticleAdmin.php
- Document/Serializer/ArticleSubscriber.php
- Document/Subscriber/ArticlePageSubscriber.php
- Document/Subscriber/PageTreeRouteSubscriber.php
- Document/Subscriber/RoutableSubscriber.php
- PageTree/PageTreeRepository.php
- Resources/phpcr-migrations/Version201712041018.php
- Tests/travis.php.ini
| Q | A
| --- | ---
Applied changes to fix style-ci and increased memory_limit for travis to fix the tests.
> Fixed style-ci and tests

- README.md
- composer.json
| Q | A
| --- | ---
This PR add a hint for conflicts in README and composer.json
> Added conflict for php 7.2 and elasticsearch 6.0

- Controller/ArticleController.php
- ListBuilder/ElasticSearchFieldDescriptor.php
- ListBuilder/ElasticSearchFieldDescriptorBuilder.php
- Resources/public/js/components/articles/list/main.js
- Tests/Functional/Controller/ArticleControllerTest.php
- Tests/Unit/ListBuilder/ElasticSearchFieldDescriptorBuilderTest.php
- Tests/app/config/config.yml
| Q | A
| --- | ---
This PR enables export for articles.
> Added export button and fixed controller without limit

- Gruntfile.js
- package.json
| Q | A
| --- | ---
Require grunt for build js.
So grunt don't need to be installed globally.
> Require grunt for build js

- Document/Subscriber/ArticleSubscriber.php
- Tests/Functional/Controller/ArticlePageControllerTest.php
- Tests/Unit/Document/Subscriber/ArticleSubscriberTest.php
| Q | A
| --- | ---
| Fixed tickets | fixes --
TODO
TODO
> Bugfix: Article page with different title

- Document/ArticleViewDocument.php
- Tests/Functional/Content/ArticleDataProviderTest.php
- Tests/Functional/Sitemap/ArticleSitemapProviderTest.php
- Tests/app/Resources/webspaces/test2.xml
- UPGRADE.md
| Q | A
| --- | ---
Fix bug when webspaceKey is more more than one word.
Not working with webspace keys which is more than one word.
> Bugfix: ES Mapping MainWebspace/AdditionalWebspaces

- Resources/translations/sulu/backend.fr.xlf
- Resources/translations/sulu/backend.nl.xlf
> Added nl/fr translations for show ghost/shadow articles

- Resources/doc/routing.md
| Q | A
| --- | ---
Added example of page_tree_route to documentation.
Code is always good.
> Added example of page_tree_route to documentation

- Resources/doc/content-types.md
| Q | A
| --- | ---
Added example for articles smart content.
Examples are always good.
See docs.
None.
> Added example for articles smart content

- .travis.yml
- Content/ArticleDataProvider.php
- Document/ArticlePageViewObject.php
- Document/CategoryViewObject.php
- Document/ExcerptViewObject.php
- Document/LocalizationStateViewObject.php
- Document/MediaViewObject.php
- Document/SeoViewObject.php
- Document/TagViewObject.php
- composer.json
| Q | A
| --- | ---
PHP 7.2 compatibility (upgraded to compatible ONGR/elasticsearch-bundle)
Personally, not aware of any BC breaks
> Fixed PHP 7.2 compatibility with ongr/elasticsearch-bundle upgrade

- EventListener/TargetWebspaceListener.php
| Q | A
| --- | ---
| Fixed tickets | fixes #354 
> Fixed PHP warning in TargetWebspaceListener

- Document/Index/ArticleIndexer.php
| Q | A
| --- | ---
This PR fixes the index of unpublished article-pages.
This abort the indexer when an unpublished article-page exists.
> Fixed index unpublished article-pages

- Controller/ArticleController.php
| Q | A
| --- | ---
This PR fixes typo in article-controller
> Fix typo in article-controller

- Content/ArticleDataProvider.php
| Q | A
| --- | ---
This PR fixes the smart-content sorting.
Sulu Core has changed the filter data
> Fix smart-content sorting

- .travis.yml
- Content/ArticleDataProvider.php
| Q | A
| --- | ---
This PR fixes the sorting by title in smart-content.
> Fix sorting by title in smart-content

- DependencyInjection/SuluArticleExtension.php
| Q | A
| --- | ---
Fix prepend page bundle
The SuluContentBundle was renamed to SuluPageBundle.
> Fix prepend page bundle

- Admin/ArticleAdmin.php
- PageTree/PageTreeRouteUpdateHandler.php
- Resources/config/services.xml
- Tests/Unit/PageTree/AutomationPageTreeUpdaterTest.php
- composer.json
| Q | A
| --- | ---
Adds compatibility to the Sulu AutomationBundle for Sulu 2.0.1
> Add compatibility to AutomationBundle

- Admin/ArticleJsConfig.php
| Q | A
| --- | ---
Fixed tabs menu not displaying any articles when specific article type is selected.
Articles not displaying in the admin area.
> BUGFIX: Fixed tabs menu not displaying any articles

- Controller/WebsiteArticleController.php
| Q | A
| --- | ---
Use new template reference syntax for preview
Preview crashes with latest changes in sulu (https://github.com/sulu/sulu/commit/481440f730932d723d1e8abd8b47b098d97b410b)
> New template reference syntax

- Content/ArticleSelectionContentType.php
- Content/SingleArticleSelectionContentType.php
- Controller/ArticleController.php
- Resources/config/services.xml
- Resources/doc/content-types.md
- Tests/Functional/Controller/ArticleControllerTest.php
- Tests/Unit/Content/ArticleSelectionContentTypeTest.php
- Tests/Unit/Content/SingleArticleSelectionContentTypeTest.php
- UPGRADE.md
- composer.json
| Q | A
| --- | ---
This PR adds a `single_article_selection`
It doesn't exist yet
~~~xml
<property name="my_article" type="single_article_selection">
<meta>
<title lang="en">My Article</title>
</meta>
</property>
~~~
> Add SingleArticleSelection

- Content/ArticleResourceItem.php
| Q | A
| --- | ---
This PR adds getter methods to Sulu\Bundle\ArticleBundle\Content\ArticleResourceItem to allow for displaying the author's id and full name in article lists.
At the moment there is no way to display the mentioned information a article list.
> Add getters for the author's id and full name

- Document/Subscriber/ArticleSubscriber.php
| Q | A
| --- | ---
Update develop
Add bugfixes.
> WIP: Update develop

- Controller/WebsiteArticleController.php
| Q | A
| --- | ---
| Related issues/PRs |  https://github.com/sulu/sulu/pull/5123
Fix correct mimetype for caching
See linked PR.
> Fix correct mimetype for caching

- Twig/ArticleViewDocumentTwigExtension.php
- composer.json
| Q | A
| --- | ---
| Fixed tickets | fixes
| Related issues/PRs | 
Fix twig extension and set supported twig versions.
Fix twig 3 support
> Fix twig extension and set supported twig versions

- Resources/doc/overview-page.md
| Q | A
| --- | ---
Update overview docs for sulu 2.0
Update of the docs needed to show the way in 2.0
> Update article pages overview controller docs

- Controller/WebsiteArticleController.php
- Document/Behavior/RoutablePageBehavior.php
- EventListener/ContentProxyListener.php
- composer.json
| Q | A
| --- | ---
Add missing variables for proper functionality.
> Add missing response and requestFormat variable

- README.md
| Q | A
| --- | ---
| Fixed tickets | -
Update the README.md requirements.
The requirements in the composer.json have changed for Sulu 2 but the readme was not updated.
> Update the README requirements by the data from composer.json

- .travis.yml
| Q | A
| --- | ---
Fixes pipeline for 7.2 and es 5.6
> Fix variables of travis pipeline

- Content/PageTreeArticleDataProvider.php
| Q | A
| --- | ---
Fix type error in `PageTreeArticleDataProvider`
> Fix type error

- .github/workflows/test-application.yaml
- README.md
- composer.json
See: https://github.com/nnatter/SuluArticleBundle/blob/enhancement/readme-structure/README.md
> Adjust README.md structure and content

- Document/Resolver/WebspaceResolver.php
| Q | A
| --- | ---
Fixed webspace resolver for empty additional webspaces.
> Fixed webspace resolver for empty additional webspaces

- Resources/phpcr-migrations/Version202005191117.php
| Q | A
| --- | ---
Add missing migration for snippets.
> Add article teaser migration for snippets

- Resources/phpcr-migrations/Version202005250920.php
| Q | A
| --- | ---
Adds missing migration for sortBy property in articles.
> Add smart-content migration for sortBy

- Resources/config/forms/article_settings.xml
| Q | A
| --- | ---
Fixed `additionalWebspaces` name in article_settings.xml.
Because additionalWebspaces didn't work.
> Bugfix addional webspaces

- Resources/doc/installation-es2.md
- Resources/doc/installation-es5.md
- composer.json
| Q | A
| --- | ---
Use elasticsearch bundle fork.
To have this important package under our control and provide bugfixes and features faster.
> Use elasticsearch bundle fork

- .circleci/config.yml
- .travis.yml
- Document/Resolver/WebspaceResolver.php
- Resources/doc/installation.md
- Tests/Functional/Content/PageTreeArticleDataProviderTest.php
- Tests/Functional/Controller/ArticleControllerTest.php
- Tests/Functional/Controller/ArticlePageControllerTest.php
- Tests/Unit/Document/Subscriber/ArticlePageSubscriberTest.php
- composer.json
| Q | A
| --- | ---
Explain the contents of the PR.
Which problem does the PR fix? (remove this section if you linked an issue above)
~~~php
// If you added new features, show examples of how to use them here
// (remove this section if not a new feature)
$foo = new Foo();
// Now we can do
$foo->doSomething();
~~~
Describe BC breaks/deprecations here. (remove this section if not needed)
> Merge/1.x to 2.x

- .travis.yml
| Q | A
| --- | ---
Fix travis ci stuck in composer update.
See https://travis-ci.org/github/sulu/SuluArticleBundle/jobs/703611612
> Fix travis ci stuck in composer update

- Admin/ArticleAdmin.php
| Q | A
| --- | ---
Order article types by configuration.
Currently its random by in the order how the operation system read the structure files.
> Order article types by configuration

- Document/Index/ArticleIndexer.php
- phpstan.neon
> Change translation domain of article type from backend to admin

- UPGRADE.md
| Q | A
| --- | ---
Fix wrong version in UPGRADE documentation.
> Fix typo in UPGRADE.md

- DependencyInjection/StructureValidatorCompilerPass.php
- composer.json
| Q | A
| --- | ---
| Related issues/PRs | https://github.com/sulu/sulu/pull/5381, https://github.com/sulu/SuluArticleBundle/pull/498
Remove default type fallback in compilerpass.
This hack should not longer be needed see comments and linked PRs.
> Remove default type fallback in compilerpass

- Document/Resolver/WebspaceResolver.php
> Fix when additional webspaces are set but empty

- Content/ArticleDataProvider.php
- Resources/config/services.xml
- Tests/Functional/Content/ArticleDataProviderTest.php
| Q | A
| --- | ---
Adds SmartContent template filtering for articles.
Describe BC breaks/deprecations here. (remove this section if not needed)
> Add SmartContent template filtering

- .php_cs.dist
- Tests/Application/Kernel.php
- Tests/Application/src/Kernel/ArticleBundleKernelBrowser.php
- Tests/Functional/Content/ArticleDataProviderTest.php
- Tests/Functional/Content/PageTreeArticleDataProviderTest.php
- Tests/Functional/Controller/ArticleControllerTest.php
- Tests/Functional/Controller/ArticlePageControllerTest.php
- Tests/Functional/Controller/VersionControllerTest.php
- Tests/Functional/Document/Index/ArticleIndexerTest.php
- Tests/Functional/Markup/ArticleLinkProviderTest.php
- Tests/Functional/Sitemap/ArticleSitemapProviderTest.php
- Tests/Functional/Teaser/ArticleTeaserProviderTest.php
- Tests/Functional/Twig/ArticleViewDocumentTwigExtensionTest.php
- composer.json
| Q | A
| --- | ---
Fix tests after symfony/browser-kit release
> Fix tests after symfony/browser-kit release
